### ISSUE TITLE
error loading file in edit mode ("a")

### ISSUE THREAD

**Issue by errearanhas** [Alexander-Barth/NCDatasets.jl#100] opened 2020-09-02 17:35 UTC
I am not able to open some netCDF files in edit mode using the "a" option.
(I am following https://alexander-barth.github.io/NCDatasets.jl/stable/#Edit-an-existing-netCDF-file-1)

**Example:**

ncdata = NCDataset("data-2000-09-06-01-1.nc", "a")
(this sample file can be downloaded from [here](https://portal.nersc.gov/project/ClimateNet/climatenet_data/))

**My environment**
- macOS Catalina 10.15.5
- Julia v1.5.0
- NCDatasets v0.10.3
 
**Error message**

```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 4554718656:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1583 in H5F_open(): file is already open for read-only
    major: File accessibilty
    minor: Unable to open file
ERROR: NetCDF error: Opening path data-2000-09-06-01-1.nc: NetCDF: HDF error (NetCDF error code: -101)
Stacktrace:
 [1] nc_open(::String, ::UInt16) at /Users/renatoaranha/.julia/packages/NCDatasets/NNX1o/src/netcdf_c.jl:281
 [2] NCDataset(::String, ::String; format::Symbol, diskless::Bool, persist::Bool, attrib::Array{Any,1}) at /Users/renatoaranha/.julia/packages/NCDatasets/NNX1o/src/dataset.jl:241
 [3] NCDataset(::String, ::String) at /Users/renatoaranha/.julia/packages/NCDatasets/NNX1o/src/dataset.jl:226
 [4] top-level scope at none:1
```

**Comment by Alexander-Barth** [comment] 2020-09-02 20:19
This could be due to 
>  file is already open for read-only

Does the error persists if you restart Julia?

**Comment by errearanhas** [comment] 2020-09-03 03:47
Initially I also thought it could be something like this. But the error persists even in a new Julia session.

**Comment by ctroupin** [comment] 2020-09-03 07:28
I've tested on my machine
Julia 1.5.1
NCDatasets v0.10.4
but cannot reproduce the problem, even if I try to open the file without closing it.
```julia
NCDataset: data-2000-09-06-01-1.nc
Group: /

Groups
  NCDataset: data-2000-09-06-01-1.nc
  Group: data

  Dimensions
     lat = 768
     lon = 1152
...
    label_11_tc     (1152 × 768)
      Datatype:    Int64
      Dimensions:  lon × lat
      Attributes:
       description          = tropical cyclone masks of labeling #11

  Global attributes
    num_labels           = 12

```

Do you do something on the file before the command `ncdata = NCDataset("data-2000-09-06-01-1.nc", "a")`?

**Comment by ctroupin** [comment] 2020-09-03 12:53
Yes, you normally do something like:
```julia
ncdata = NCDataset("data-2000-09-06-01-1.nc", "a")

   [some operations]

close(ncdata)
```

or another way is to use *Do block* syntax:
```julia
NCDataset("data-2000-09-06-01-1.nc", "a") do ncdata

   [some operations]

end
```

**Comment by errearanhas** [comment] 2020-09-05 00:44
Nice. That solved the problem. Thank you, @ctroupin!

**Comment by ctroupin** [comment] 2020-09-06 14:53
Thanks, you're welcome!

**Closed by ctroupin** 2020-09-06 14:53 UTC
