### ISSUE TITLE
Incorrectly handeling attributes scale_factor and add_offset

### ISSUE THREAD

**Issue by melodyjulia** [Alexander-Barth/NCDatasets.jl#95] opened 2020-08-12 12:09 UTC
**Describe the bug**

Use Dataset() to open multiple netCDF files with scale_factor and add_offset attributes, usually  each file has different values assigned to scale_factor or add_offset. It seems NCDatasets.jl assuming same scale_factor and add_offset values for all files by using their values from the first file. Therefore, variables read by NCDataset.jl only have correct values for the first file.

**Environment**

 - operating system: Debian, Linux 4.9.0-12
 - Julia version: [e.g. julia 1.0.5, official binaries from https://julialang.org/downloads/]
 - NCDatasets version: v0.10.2

**Reproduce the bug**
Please use the following code and data. Two netCDF files can be generated using ncgen utility and the CDL files.

**Code**

using NCDatasets

f1 = Dataset("f1.nc")
f2 = Dataset("f2.nc")

skt1 = f1["skt"][:]
skt2 = f2["skt"][:]

println("first bunch data")
println(skt1)

println("second bunch data")
println(skt2)

close(f1)
close(f2)

files = ["f1.nc", "f2.nc"]

fx = Dataset(files)

skt = fx["skt"][:]

n = size(skt1)[1]

println("first bunch data")
println(skt[1:n])

println("second bunch data")
println(skt[(n+1):end])

close(fx)

**CDL file for f1.nc**

netcdf f1 {
dimensions:
	time = UNLIMITED ;
variables:
	short skt(time) ;
		skt:longitude = 0.f ;
		skt:latitude = 90.f ;
		skt:scale_factor = 0.0023746899988156 ;
		skt:add_offset = 262.629694918184 ;
		skt:_FillValue = -32767s ;
		skt:missing_value = -32767s ;
		skt:units = "K" ;
		skt:long_name = "Skin temperature" ;
	int time(time) ;
		time:units = "hours since 1900-01-01 00:00:00.0" ;
		time:long_name = "time" ;
		time:calendar = "gregorian" ;
data:

 skt = -6419, -5524, -5580, -6284, -6711, -6717, -7089, -7549, -7777, -7991, 
    -8205, -8082, -8180, -8212, -8353, -8136, -7833, -7096, -5701, -4588, 
    -3818, -3618, -3666, -3375, -3593, -3839, -4785, -5826, -6281, -6233, 
    -4874, -3452, -3015, -3465, -4367, -4693, -5439, -6197, -5707, -5195, 
    -4658, -4247, -3614, -3779, -4770, -4354, -3881, -4037, -3806, -3320, 
    -2661, -3131, -3113, -2772, -3601, -4499, -5331, -5794, -6126, -6489, 
    -6939, -7484, -7802, -8172, -8456, -8490, -8144, -7262, -6881, -7040, 
    -7237, -7115, -7308, -7910, -8042, -7754, -7465, -7616, -7473, -7163, 
    -7500, -8095, -8166, -7783, -7380, -7615, -6945, -6009, -5112, -5388, 
    -5524, -4907, -5055, -5429, -5828, -6426, -6800, -7172, -7465, -7812, 
    -7988, -7504, -7400, -7174, -7242, -7271, -6907, -6538, -6261, -6342, 
    -6410, -6696, -7235, -7303, -7249, -7315, -6957, -6531, -6078, -6672, 
    -6661, -7045, -7197, -7755 ;

 time = 1008072, 1008078, 1008084, 1008090, 1008096, 1008102, 1008108, 
    1008114, 1008120, 1008126, 1008132, 1008138, 1008144, 1008150, 1008156, 
    1008162, 1008168, 1008174, 1008180, 1008186, 1008192, 1008198, 1008204, 
    1008210, 1008216, 1008222, 1008228, 1008234, 1008240, 1008246, 1008252, 
    1008258, 1008264, 1008270, 1008276, 1008282, 1008288, 1008294, 1008300, 
    1008306, 1008312, 1008318, 1008324, 1008330, 1008336, 1008342, 1008348, 
    1008354, 1008360, 1008366, 1008372, 1008378, 1008384, 1008390, 1008396, 
    1008402, 1008408, 1008414, 1008420, 1008426, 1008432, 1008438, 1008444, 
    1008450, 1008456, 1008462, 1008468, 1008474, 1008480, 1008486, 1008492, 
    1008498, 1008504, 1008510, 1008516, 1008522, 1008528, 1008534, 1008540, 
    1008546, 1008552, 1008558, 1008564, 1008570, 1008576, 1008582, 1008588, 
    1008594, 1008600, 1008606, 1008612, 1008618, 1008624, 1008630, 1008636, 
    1008642, 1008648, 1008654, 1008660, 1008666, 1008672, 1008678, 1008684, 
    1008690, 1008696, 1008702, 1008708, 1008714, 1008720, 1008726, 1008732, 
    1008738, 1008744, 1008750, 1008756, 1008762, 1008768, 1008774, 1008780, 
    1008786, 1008792, 1008798, 1008804, 1008810 ;
}

**CDL file for f2.nc**

netcdf f2 {
dimensions:
	time = UNLIMITED;
variables:
	short skt(time) ;
		skt:longitude = 0.f ;
		skt:latitude = 90.f ;
		skt:scale_factor = 0.00236771058077967 ;
		skt:add_offset = 259.449209821467 ;
		skt:_FillValue = -32767s ;
		skt:missing_value = -32767s ;
		skt:units = "K" ;
		skt:long_name = "Skin temperature" ;
	int time(time) ;
		time:units = "hours since 1900-01-01 00:00:00.0" ;
		time:long_name = "time" ;
		time:calendar = "gregorian" ;
data:

 skt = -6548, -6930, -7100, -7645, -7935, -7920, -7953, -7185, -7131, -6820, 
    -6734, -5450, -3851, -3470, -3148, -4736, -5399, -5436, -4603, -4194, 
    -4139, -4017, -4429, -4720, -4739, -4419, -4147, -3374, -2907, -3469, 
    -3221, -2197, -1803, -2349, -2506, -2507, -2130, -1730, -1425, -684, 
    -337, -1051, -1358, -1397, -1542, -2045, -3042, -3220, -2912, -2580, 
    -2839, -3067, -3261, -2962, -2996, -3377, -3757, -4463, -4807, -5175, 
    -5193, -4899, -4249, -4226, -4217, -4870, -5191, -4130, -3350, -3478, 
    -3856, -3833, -3994, -4163, -4004, -3343, -2835, -2814, -2644, -2185, 
    -1881, -1948, -2053, -1810, -1129, -1528, -1688, -1841, -1739, -1696, 
    -134, -681, -1105, -1917, -2231, -1401, -1060, -1187, -1691, -2253, 
    -2550, -3347, -3344, -3359, -2777, -2511, -2635, -2802, -2695, -2720, 
    -3102, -3795 ;

 time = 1008816, 1008822, 1008828, 1008834, 1008840, 1008846, 1008852, 
    1008858, 1008864, 1008870, 1008876, 1008882, 1008888, 1008894, 1008900, 
    1008906, 1008912, 1008918, 1008924, 1008930, 1008936, 1008942, 1008948, 
    1008954, 1008960, 1008966, 1008972, 1008978, 1008984, 1008990, 1008996, 
    1009002, 1009008, 1009014, 1009020, 1009026, 1009032, 1009038, 1009044, 
    1009050, 1009056, 1009062, 1009068, 1009074, 1009080, 1009086, 1009092, 
    1009098, 1009104, 1009110, 1009116, 1009122, 1009128, 1009134, 1009140, 
    1009146, 1009152, 1009158, 1009164, 1009170, 1009176, 1009182, 1009188, 
    1009194, 1009200, 1009206, 1009212, 1009218, 1009224, 1009230, 1009236, 
    1009242, 1009248, 1009254, 1009260, 1009266, 1009272, 1009278, 1009284, 
    1009290, 1009296, 1009302, 1009308, 1009314, 1009320, 1009326, 1009332, 
    1009338, 1009344, 1009350, 1009356, 1009362, 1009368, 1009374, 1009380, 
    1009386, 1009392, 1009398, 1009404, 1009410, 1009416, 1009422, 1009428, 
    1009434, 1009440, 1009446, 1009452, 1009458, 1009464, 1009470, 1009476, 
    1009482 ;
}

**Comment by melodyjulia** [comment] 2020-08-20 13:09
Updated with sample code and data.

**Comment by Alexander-Barth** [comment] 2020-09-09 10:11
Actually, it is assumed that all NetCDF files have the same attributes. It was not clear in the document when you wrote the issue but I have added this.
The reason this limitation exists is that `ds["var"].attrib["scale_factor"]` would become ambiguous if  every netCDF files would define a different `scale_factor` (if ds is a multi-file data set)

**Comment by melodyjulia** [comment] 2020-09-09 12:32
Each file has its own values for ds["var"].attrib["scale_factor"] and ds["var"].attrib["add_offset"] is reasonable, the situation becomes ambiguous when these files are opened in a multi-file dataset way, we might need to track "scale_factor" and "add_offset" for each file. I found currently python package xarray handles this issue successfully.

**Comment by melodyjulia** [comment] 2020-09-09 13:51
I'm wondering if it's possible to hide "scale_factor" and "add_offset" attributes in the dataset when files are opened in a multi-file fashion, as the two attributes are special for each file. When accessing the values of ds["var"], NCDataset.jl checks if "scale_factor" and "add_offset" are available and does conversion automatically.

**Comment by Alexander-Barth** [comment] 2020-10-27 21:04
Duplicate of #95

**Comment by visr** [comment] 2020-10-27 21:27
Did you mean to close #109 as a duplicate of this issue instead? #95 === #95 :)

**Comment by Alexander-Barth** [comment] 2020-10-27 21:57
Yes, that is what I meant. Need rest :-)

**Comment by Datseris** [comment] 2020-10-28 13:00
> The reason this limitation exists is that ds["var"].attrib["scale_factor"] would become ambiguous if every netCDF files would define a different scale_factor (if ds is a multi-file data set)

Doesn't it make more sense to be able to load multi-file sets and instead to not add an entry to `attrib["scale_factor"]`? To me the fact that loading is incorrect seems like a much, much bigger problem...

**Comment by Alexander-Barth** [comment] 2020-10-29 06:12
Yes, I agree. We probably need a new type `MFCFVariable` (multi-file variable using the CF conventions) to handle this case. 

Potential corner case: the effective type (i.e. the type after transformation following the CF conventions) could be different for different files. But for me, we can require that all the types of `scale_factor`, `add_offset` and the variable type are the same in all files (and likewise the `calendar` attribute value for time variables) to simplify.

**Comment by Datseris** [comment] 2020-10-29 07:37
But even in this corner case, why not just `promote_type`? You can _warn_ that the type changes, but is it really necessary to _require_ it?

**Comment by Alexander-Barth** [comment] 2020-10-29 07:42
Yes, for `scale_factor` and `add_offset` one can use `promote_type`. But it would require to open all NetCDF files (which can be slow if they are OPENDAP resources). But for a varying `calendar` attribute, you cannot do that (e.g. DateTime and DateTime360Day)

**Comment by Datseris** [comment] 2020-10-29 07:59
Okay, good point.

**Comment by Datseris** [comment] 2022-02-24 13:06
I don't know how to contribute here, but addressing this would be nice. It really makes for a bad workflow to have to load half my data with NCDatasets.jl and the other half with Python's xarray...

**Comment by Alexander-Barth** [comment] 2022-04-15 05:41
This issue should now be fixed in master. Please reopen with a reproducer if this is not the case. Thanks you all for contributing to the discussion.

**Closed by Alexander-Barth** 2022-04-15 05:41 UTC
