### ISSUE TITLE
NCDatasets fails to load on Julia 1.6-beta1

### ISSUE THREAD

**Issue by Alexander-Barth** [Alexander-Barth/NCDatasets.jl#118] opened 2021-01-12 08:21 UTC
**Describe the bug**

NCDatasets fails to load on Julia 1.6.0-beta1

**To Reproduce**

```julia
using NCDatasets
```

**Environment**

 - operating system:  Ubuntu 18.04
 - julia 1.6.0-beta 1 official binaries from https://julialang.org/downloads/
 - NCDatasets version: master
 
**Full output**

```
julia> using NCDatasets
[ Info: Precompiling NCDatasets [85f8d34a-cbdd-5861-8df4-14fed0d494ab]
ERROR: LoadError: InitError: could not load library "/home/abarth/.julia/artifacts/877149aedda703fde4a848bffd955df8934ca876/lib/libnetcdf.so"
libmbedtls.so.12: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:114
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:114
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/WnWcZ/src/products/library_generators.jl:63 [inlined]
  [4] __init__()
    @ NetCDF_jll ~/.julia/packages/NetCDF_jll/y27Nj/src/wrappers/x86_64-linux-gnu.jl:14
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:670
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:756
  [7] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:994
  [8] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:910
  [9] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:897
 [10] include
    @ ./Base.jl:386 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1209
 [12] top-level scope
    @ none:1
 [13] eval
    @ ./boot.jl:360 [inlined]
 [14] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [15] top-level scope
    @ none:1
```

**Comment by Alexander-Barth** [comment] 2021-01-12 08:23
The issue is known upstream and related to  MbedTLS:
https://github.com/JuliaLang/julia/issues/39015

**Comment by visr** [comment] 2021-02-18 22:10
Was fixed by 446255368c22d61b35dc9a24b4ac347ee5f80379

**Closed** 2021-03-01 08:59 UTC

**Comment by cgeoga** [comment] 2021-04-06 19:13
Hi, apologies if this is better as a new issue than as a comment on a closed issue, but I'm experiencing this issue now in Fedora 33/julia v1.6/NCDatasets v0.11.3, and it happens in a perfectly fresh `~/.julia`, so I think that rules out some other dependency relying on an old version of something and making trouble. I'm having a little trouble following these threads about what the issue is, but is there some kind of hacky thing I can do immediately to start using a local fork of this package at least? Like, can I rename a `.so` file or something? Searching for `libmbedtls.so.*` in my `~/.julia` folder gives no results, including after a manual add of the `MbedTLS` package, so maybe not. But if you have any suggestions I'd really appreciate hearing them.

**Comment by Alexander-Barth** [comment] 2021-04-06 20:25
Yes, filling a new issue would be good idea. It works for me on Ubuntu 20.04 and CentOS Linux release 8.2.2004 with julia 1.6.
Can you provide the error message that you are seeing, the output of the env. variable $PATH, $LD_LIBRARY_PATH and $LD_PRELOAD? 

Can you check if this works?

```julia
]add NetCDF_jll
using NetCDF_jll
```
